# Generated by Django 4.0.2 on 2022-02-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('courseCode', models.CharField(max_length=4)),
                ('sectionNumber', models.IntegerField(max_length=2)),
                ('faculty', models.CharField(max_length=32)),
                ('professor', models.CharField(max_length=32)),
                ('professorEmail', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('courseCode', 'sectionNumber')},
            },
        ),
    ]
