# Generated by Django 4.0.2 on 2022-02-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='sectionNumber',
            field=models.IntegerField(),
        ),
    ]
