# Generated by Django 4.0.2 on 2022-02-21 16:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField(max_length=2)),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('major', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usertag')),
            ],
        ),
    ]
