# Generated by Django 4.0.2 on 2022-02-28 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('year', models.IntegerField()),
                ('userName', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('major', models.CharField(max_length=32)),
                ('school', models.CharField(max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('tag', models.ManyToManyField(to='users.UserTag')),
            ],
        ),
    ]
