# Generated by Django 4.0.2 on 2022-02-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usertag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(),
        ),
    ]
