# Generated by Django 4.0.2 on 2022-02-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_tag_alter_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(max_length=2),
        ),
    ]
