# Generated by Django 4.0.2 on 2022-03-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0004_remove_user_tag_alter_user_courses_delete_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='courses.Course'),
        ),
    ]
