# Generated by Django 4.0.2 on 2022-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.ManyToManyField(to='users.UserTag'),
        ),
    ]
