# Generated by Django 4.0.2 on 2022-02-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'created_by', 'posted_in')},
        ),
    ]
