# Generated by Django 4.0.2 on 2022-02-28 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_coursecode_alter_course_name'),
        ('channels', '0002_delete_meta_alter_post_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
