# Generated by Django 4.0.2 on 2022-03-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_remove_post_tag_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='course',
        ),
    ]
