# Generated by Django 4.0.2 on 2022-02-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_coursecode_alter_course_name'),
        ('channels', '0003_channel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='course',
            field=models.ForeignKey(default='NoCourse', on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
