# Generated by Django 4.0.2 on 2022-03-24 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_isadmin'),
        ('channels', '0003_remove_channel_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField(max_length=255)),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now)),
                ('readFlag', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ['-dateSent'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_posted']},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(to='users.User'),
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
