# Generated by Django 4.0.2 on 2022-03-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_message_alter_post_options_remove_channel_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=32)),
            ],
        ),
    ]
