# Generated by Django 4.0.2 on 2022-03-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_tag_alter_user_courses_delete_usertag'),
        ('channels', '0004_remove_post_tags_topic_message_post_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-dateSent']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_posted']},
        ),
        migrations.RemoveField(
            model_name='channel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topics',
        ),
        migrations.AddField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(to='users.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='readFlag',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
