# Generated by Django 4.0.2 on 2022-03-26 23:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_courses'),
        ('courses', '0002_course_year_alter_course_faculty'),
        ('channels', '0005_posttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.TextField(max_length=255)),
                ('reply_date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.post')),
            ],
            options={
                'ordering': ['reply_date'],
            },
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
        migrations.AddField(
            model_name='channel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
