# Generated by Django 4.0.2 on 2022-03-27 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_reply_delete_posttag_channel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
